# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.debug=false
# Dev_ver
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.169
neo_version_range=[21.1.0,)
loader_version_range=[4,)
# Mod_info
mod_id=improved_animations
mod_name=Improved Animations
mod_license=MIT
mod_version=1.0.2
mod_group_id=einstein.improved_animations
mod_authors=Qboi123, DrAlpha, MincraftEinstein, MapleSugar365
mod_description=Minecraft Animations Mod.